# Generated by Django 5.0.6 on 2024-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid19', 'Covid19'), ('Immunization', 'Immunization')], max_length=50),
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_draft',
            new_name='draft',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
